//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoService_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersSet
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Status { get; set; }
        public int Id_Employee { get; set; }
        public int Id_Client { get; set; }
        public int Id_Service { get; set; }
    
        public virtual ClientsSet ClientsSet { get; set; }
        public virtual EmployesSet EmployesSet { get; set; }
        public virtual ServicesSet ServicesSet { get; set; }
    }
}
